# Generated by Django 3.0.5 on 2020-04-07 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stayhome', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Corona',
        ),
    ]
