# Generated by Django 3.0.5 on 2020-04-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stayhome', '0002_delete_corona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabliki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabliki', models.IntegerField()),
                ('nontab', models.IntegerField()),
            ],
        ),
    ]
